/**
* @file tpApp1Code.hpp
 * Generated by VisibleSim BlockCode Generator
 * @date 2026-09-02
 **/

#ifndef tpApp1Code_H_
#define tpApp1Code_H_

#include "robots/blinkyBlocks/blinkyBlocksSimulator.h"
#include "robots/blinkyBlocks/blinkyBlocksWorld.h"
#include "robots/blinkyBlocks/blinkyBlocksBlockCode.h"

static const int BROADCAST_MSG_ID = 1001;
static const int ACKNOWLEDGE_MSG_ID = 1002;

using namespace BlinkyBlocks;

class TpApp1Code : public BlinkyBlocksBlockCode {
private:
    BlinkyBlocksBlock *module = nullptr;

    // Private variables required by the algorithm & XML parser
    bool isLeader = false;
    Color myColor = GREY;
    int distance = 999;                     // Distance metric to leader node
    P2PNetworkInterface *parent = nullptr;  // Interface pointing back to leader parent

public:
    TpApp1Code(BlinkyBlocksBlock *host);
    ~TpApp1Code() {};

    /**
     * @brief Called on startup of the blockCode when simulation begins
     */
    void startup() override;

    /**
     * @brief Message handler for broadcast/flood messages
     */
    void myBroadcastFunc(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender);

    /**
     * @brief Message handler for acknowledge/ack2parent messages
     */
    void myAcknowledgeFunc(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender);

    /**
     * @brief Parses individual block attributes (e.g., leader="true") from XML
     */
    void parseUserBlockElements(TiXmlElement *config) override;

    /**
     * @brief Parses global parameters (e.g., myColor) from XML
     */
    void parseUserElements(TiXmlDocument *config) override;

    void onUserArrowKeyPressed(unsigned char c, int x, int y) override;
    void onTap(int face) override;

    static BlockCode *buildNewBlockCode(BuildingBlock *host) {
        return (new TpApp1Code((BlinkyBlocksBlock*)host));
    }
};

#endif /* tpApp1Code_H_ */