/**
 * @file tpApp1Code.cpp
 * Generated by VisibleSim BlockCode Generator
 * @date 2026-09-02
 **/

#include "tpApp1Code.hpp"

TpApp1Code::TpApp1Code(BlinkyBlocksBlock *host) : BlinkyBlocksBlockCode(host), module(host) {
    if (not host) return;

    // Register callback for broadcast/flood messages
    addMessageEventFunc2(BROADCAST_MSG_ID,
                       std::bind(&TpApp1Code::myBroadcastFunc, this,
                       std::placeholders::_1, std::placeholders::_2));

    // Register callback for acknowledge messages
    addMessageEventFunc2(ACKNOWLEDGE_MSG_ID,
                       std::bind(&TpApp1Code::myAcknowledgeFunc, this,
                       std::placeholders::_1, std::placeholders::_2));
}

// Global XML parameter parser
void TpApp1Code::parseUserElements(TiXmlDocument *config) {
    TiXmlNode *node = config->FirstChild("parameters");
    if (!node) return;

    TiXmlElement *element = node->ToElement();
    const char *attr = element->Attribute("myColor");

    if (attr) {
        myColor = Simulator::extractColorFromString(attr);
        std::cout << "myColor = " << myColor << std::endl;
    } else {
        myColor = GREY;
    }
}

// Block-specific XML attribute parser
void TpApp1Code::parseUserBlockElements(TiXmlElement *config) {
    const char *attr = config->Attribute("leader");
    isLeader = (attr ? Simulator::extractBoolFromString(attr) : false);

    if (isLeader) {
        std::cout << getId() << " is leader!" << std::endl;
    }
}

// Startup method executed when pressing 'r' or 'R'
void TpApp1Code::startup() {
    console << "start " << getId() << "\n";

    if (isLeader) {
        distance = 0;
        setColor(BLACK); // Changed leader color to BLACK

        // Broadcast initial flooding message to all connected neighbors
        for (int i = 0; i < module->getNbInterfaces(); i++) {
            P2PNetworkInterface *p2p = module->getInterface(i);
            if (p2p->isConnected()) {
                p2p->send(new MessageOf<pair<int, int>>(BROADCAST_MSG_ID, make_pair(distance + 1, getId())));
                console << "sends distance(" << distance + 1 << "," << getId() << ") to " << p2p->getConnectedBlockId() << "\n";
            }
        }
    }
}

void TpApp1Code::myBroadcastFunc(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender) {
    MessageOf<pair<int, int>>* msg = static_cast<MessageOf<pair<int, int>>*>(_msg.get());
    pair<int, int> msgData = *msg->getData();

    int recDistance = msgData.first;
    int senderId = msgData.second;

    console << "rec. Flood (" << recDistance << "," << senderId << ") from " << sender->getConnectedBlockId() << "\n";

    // If a shorter path/distance is received
    if (recDistance < distance) {
        distance = recDistance;
        parent = sender;

        // Assign colors dynamically based on hop distance from leader
        switch (distance) {
            case 1: setColor(CYAN); break;
            case 2: setColor(GREEN); break;
            case 3: setColor(YELLOW); break;
            case 4: setColor(ORANGE); break;
            case 5: setColor(WHITE); break;
            case 6: setColor(MAGENTA); break;
            case 7: setColor(PINK); break;
            default: setColor(BLUE); break;
        }

        // Forward distance metric to connected neighbors (except the sender)
        for (int i = 0; i < module->getNbInterfaces(); i++) {
            P2PNetworkInterface *p2p = module->getInterface(i);
            if (p2p->isConnected() && p2p != sender) {
                p2p->send(new MessageOf<pair<int, int>>(BROADCAST_MSG_ID, make_pair(distance + 1, getId())));
                console << "sends distance(" << distance + 1 << "," << getId() << ") to " << p2p->getConnectedBlockId() << "\n";
            }
        }

        // Send acknowledgment back to parent interface
        if (parent) {
            parent->send(new MessageOf<int>(ACKNOWLEDGE_MSG_ID, getId()));
            console << "sends ack2parent to " << parent->getConnectedBlockId() << "\n";
        }
    }
}

void TpApp1Code::myAcknowledgeFunc(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender) {
    MessageOf<int>* msg = static_cast<MessageOf<int>*>(_msg.get());
    int ackSenderId = *msg->getData();

    console << "rec. Ack(" << ackSenderId << ") from " << sender->getConnectedBlockId() << "\n";
}

void TpApp1Code::onUserArrowKeyPressed(unsigned char c, int x, int y) {
    switch (c) {
        case GLUT_KEY_LEFT:
            std::cout << "key left" << std::endl;
            break;
        case GLUT_KEY_RIGHT:
            std::cout << "key right" << std::endl;
            break;
    }
}

void TpApp1Code::onTap(int face) {
    std::cout << "Block 'tapped': " << getId() << std::endl;
}