/**
 * @file tpApp1Code.cpp
 * Generated by VisibleSim BlockCode Generator
 * https://services-stgi.nfc.univ-fcomte.fr/visiblesim/generator.php#
 * @author yourName
 * @date 2022-09-22
 **/

#include "tpApp1Code.hpp"

TpApp1Code::TpApp1Code(BlinkyBlocksBlock *host):BlinkyBlocksBlockCode(host),module(host) {
  // @warning Do not remove block below, as a blockcode with a NULL host might be created
  //  for command line parsing
  if (not host) return;

  // Registers a callback (myBroadcastFunc) to the message of type R
  addMessageEventFunc2(BROADCAST_MSG_ID,
                       std::bind(&TpApp1Code::myBroadcastFunc,
                                 this,
                                 std::placeholders::_1,
                                 std::placeholders::_2)
                       );

  // Registers a callback (myAcknowledgeFunc) to the message of type K
  addMessageEventFunc2(ACKNOWLEDGE_MSG_ID,
                       std::bind(&TpApp1Code::myAcknowledgeFunc,
                                 this,
                                 std::placeholders::_1,
                                 std::placeholders::_2)
                       );
}

void TpApp1Code::startup() {
  console << "start " << getId() << "\n";

  distance = 0;
  currentRound = 0;
  parent = nullptr;

  if (isLeader) {
    startElection();
  }
}

void TpApp1Code::startElection() {
  // Become (or re-become) the leader / root of the gradient.
  isLeader = true;
  parent = nullptr;
  distance = 0;
  currentRound++;              // new epoch: overrides any gradient from a previous leader

  module->setColor(RED);

  console << getId() << " is the new leader! (round " << currentRound << ")\n";

  string str = "distance(1," + to_string(currentRound) + ")";
  nbWaitedAnswers = sendMessageToAllNeighbors(
                       str.c_str(),
                       new MessageOf<pair<int,int>>(BROADCAST_MSG_ID, make_pair(distance+1,currentRound)),
                       1000,100,0);
}

void TpApp1Code::myBroadcastFunc(std::shared_ptr<Message>_msg, P2PNetworkInterface*sender) {
  MessageOf<pair<int,int>>* msg = static_cast<MessageOf<pair<int,int>>*>(_msg.get());
  pair<int,int> msgData = *msg->getData();
  int newDistance = msgData.first;
  int newRound     = msgData.second;

  console << "rec. Flood (" << newDistance << "," << newRound << ") from " << sender->getConnectedBlockId() << "\n";

  // Accept only the FIRST message we see for a given round (i.e. a strictly
  // newer round than the one we're currently on). On graphs with cycles/loops,
  // a block can be reached via more than one path; if we let a later "shorter"
  // message re-trigger forwarding after we've already started propagating,
  // the block we originally forwarded to (our old parent) would wait forever
  // for an acknowledgment that never comes, and the wave never completes.
  // So: whichever message arrives first for a round wins; anything else for
  // that same (or an older) round is just acknowledged, not re-propagated.
  bool newerRound = (newRound > currentRound);

  if (newerRound) {
    distance = newDistance;
    currentRound = newRound;
    setColor(distance);
    parent = sender;
    string str = "distance(" + to_string(distance+1) + "," + to_string(currentRound) + ")";
    nbWaitedAnswers = sendMessageToAllNeighbors(
                         str.c_str(),
                         new MessageOf<pair<int,int>>(BROADCAST_MSG_ID, make_pair(distance+1,currentRound)),
                         1000,100,1,sender);
    if (nbWaitedAnswers==0) {
      sendMessage("ack2parent",new Message(ACKNOWLEDGE_MSG_ID),parent,1000,100);
    }
  } else {
    sendMessage("ack2sender",new Message(ACKNOWLEDGE_MSG_ID),sender,1000,100);
  }
}

void TpApp1Code::myAcknowledgeFunc(std::shared_ptr<Message>_msg, P2PNetworkInterface*sender) {
  nbWaitedAnswers--;
  console << "rec. Ack(" << nbWaitedAnswers << ") from " << sender->getConnectedBlockId() << "\n";
  if (nbWaitedAnswers==0) {
    if (parent==nullptr) {
      setColor(BLACK);
    } else {
      sendMessage("ack2parent",new Message(ACKNOWLEDGE_MSG_ID),parent,1000,100);
    }
  }
}

void TpApp1Code::parseUserBlockElements(TiXmlElement *config) {
  const char *attr = config->Attribute("leader");
  isLeader = (attr?Simulator::extractBoolFromString(attr):false);
  if (isLeader) {
    std::cout << getId() << " is leader!" << std::endl;
  }
}

void TpApp1Code::onUserKeyPressed(unsigned char c, int x, int y) {
  switch (c) {
    case 'a' :
      std::cout << "key a" << endl;
      break;
    case 'd' : break;
  }
}

void TpApp1Code::onTap(int face) {
  std::cout << "Block tapped: " << getId() << " -> becoming the new leader" << std::endl;
  startElection();
}