
/**
 * @file tpApp1Code.cpp
 * Generated by VisibleSim BlockCode Generator
 * https://services-stgi.pu-pm.univ-fcomte.fr/visiblesim/generator.php#
 * @author yourName
 * @date 2026-09-02                                                                     
 **/
 
#include "tpApp1Code.hpp"

TpApp1Code::TpApp1Code(BlinkyBlocksBlock *host):BlinkyBlocksBlockCode(host),module(host) {
    // @warning Do not remove block below, as a blockcode with a NULL host might be created
    //  for command line parsing
    if (not host) return;

    // Registers a callback (myBroadcastFunc) to the message of type R
    addMessageEventFunc2(BROADCAST_MSG_ID,
                       std::bind(&TpApp1Code::myBroadcastFunc,this,
                       std::placeholders::_1, std::placeholders::_2));

    // Registers a callback (myAcknowledgeFunc) to the message of type K
    addMessageEventFunc2(ACKNOWLEDGE_MSG_ID,
                       std::bind(&TpApp1Code::myAcknowledgeFunc,this,
                       std::placeholders::_1, std::placeholders::_2));

}

void TpApp1Code::startup() {
    console << "start " << getId() << "\n";

    if (isLeader) { // At least one module must be "leader" in the config file
        setColor(RED);
    }	
}
void TpApp1Code::myBroadcastFunc(std::shared_ptr<Message>_msg, P2PNetworkInterface*sender) {
    MessageOf<pair<int,int>>* msg = static_cast<MessageOf<pair<int,int>>*>(_msg.get());
    pair<int,int> msgData = *msg->getData();

}

void TpApp1Code::myAcknowledgeFunc(std::shared_ptr<Message>_msg, P2PNetworkInterface*sender) {
}


void TpApp1Code::parseUserBlockElements(TiXmlElement *config) {
    const char *attr = config->Attribute("leader");
    isLeader = (attr?Simulator::extractBoolFromString(attr):false);
    if (isLeader) {
        std::cout << getId() << " is leader!" << std::endl; // complete with your code
    }
}

void TpApp1Code::onUserArrowKeyPressed(unsigned char c, int x, int y) {
    switch (c) {
        case GLUT_KEY_LEFT:
            std::cout << "key left" << endl;
            
        break;
        case GLUT_KEY_RIGHT:
            std::cout << "key right" << endl; 
        break;
    }
}

void TpApp1Code::onTap(int face) {
    std::cout << "Block 'tapped':" << getId() << std::endl; // complete with your code here
}
